// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVPk25zEfsNfEJ8V0R_dz9A6s7mpg8y3I',
    appId: '1:267379765781:web:73c5a124591c28a1a8141c',
    messagingSenderId: '267379765781',
    projectId: 'task-management-babf6',
    authDomain: 'task-management-babf6.firebaseapp.com',
    storageBucket: 'task-management-babf6.firebasestorage.app',
    measurementId: 'G-6VXT3LKSBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyXErwtwvbFLGomHXUZWvaIeTO_weTGE',
    appId: '1:267379765781:android:168911e9bab4d1f6a8141c',
    messagingSenderId: '267379765781',
    projectId: 'task-management-babf6',
    storageBucket: 'task-management-babf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeH5xBooZ0lAuWKwgKjEXaYmRAoEk5Sdw',
    appId: '1:267379765781:ios:bd717fbb23621098a8141c',
    messagingSenderId: '267379765781',
    projectId: 'task-management-babf6',
    storageBucket: 'task-management-babf6.firebasestorage.app',
    iosBundleId: 'com.example.taskMgmt',
  );
}
